import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...);

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Java Design Patterns sidebar
  designPatterns: [
    {
      type: "category",
      label: "📖 概览与参考",
      collapsed: false,
      items: [
        "java-design-patterns/index",
        "java-design-patterns/overview",
        "java-design-patterns/quick-reference",
        "java-design-patterns/best-practices",
        "java-design-patterns/scenarios",
        "java-design-patterns/selection-guide",
        "java-design-patterns/interview-questions",
      ],
    },
    {
      type: "category",
      label: "创建型模式 (5)",
      collapsed: false,
      items: [
        "java-design-patterns/singleton-pattern",
        "java-design-patterns/factory-pattern",
        "java-design-patterns/abstract-factory-pattern",
        "java-design-patterns/builder-pattern",
        "java-design-patterns/prototype-pattern",
      ],
    },
    {
      type: "category",
      label: "结构型模式 (7)",
      collapsed: false,
      items: [
        "java-design-patterns/proxy-pattern",
        "java-design-patterns/adapter-pattern",
        "java-design-patterns/decorator-pattern",
        "java-design-patterns/facade-pattern",
        "java-design-patterns/composite-pattern",
        "java-design-patterns/flyweight-pattern",
        "java-design-patterns/bridge-pattern",
      ],
    },
    {
      type: "category",
      label: "行为型模式 (11)",
      collapsed: false,
      items: [
        "java-design-patterns/observer-pattern",
        "java-design-patterns/strategy-pattern",
        "java-design-patterns/template-method-pattern",
        "java-design-patterns/command-pattern",
        "java-design-patterns/iterator-pattern",
        "java-design-patterns/state-pattern",
        "java-design-patterns/chain-of-responsibility-pattern",
        "java-design-patterns/mediator-pattern",
        "java-design-patterns/memento-pattern",
        "java-design-patterns/visitor-pattern",
        "java-design-patterns/interpreter-pattern",
      ],
    },
  ],

  // Spring sidebar
  spring: [
    {
      type: "autogenerated",
      dirName: "spring",
    },
  ],

  // Spring Boot sidebar
  springboot: [
    {
      type: "autogenerated",
      dirName: "springboot",
    },
  ],

  // Netty sidebar
  netty: [
    {
      type: "autogenerated",
      dirName: "netty",
    },
  ],

  // Java Programming sidebar
  java: [
    {
      type: "autogenerated",
      dirName: "java",
    },
  ],

  // Rust Programming sidebar
  rust: [
    {
      type: "autogenerated",
      dirName: "rust",
    },
  ],

  // Linux sidebar
  linux: [
    {
      type: "autogenerated",
      dirName: "linux",
    },
  ],

  // React sidebar
  react: [
    {
      type: "autogenerated",
      dirName: "react",
    },
  ],

  // MySQL sidebar
  mysql: [
    {
      type: "autogenerated",
      dirName: "mysql",
    },
  ],

  // Redis sidebar
  redis: [
    "redis/index",
    {
      type: "autogenerated",
      dirName: "redis",
    },
  ],

  // Spring Cloud sidebar
  springcloud: [
    "springcloud/index",
    {
      type: "autogenerated",
      dirName: "springcloud",
    },
  ],

  // Spring Cloud Alibaba sidebar
  springcloudAlibaba: [
    "springcloud-alibaba/index",
    {
      type: "autogenerated",
      dirName: "springcloud-alibaba",
    },
  ],
};

export default sidebars;
