import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...);

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 使用自动生成模式，通过 _category_.json 文件自定义每个分类的显示
  // 这样可以保持简洁同时支持自定义
  docs: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default sidebars;
